### ISSUE TITLE
打开非flutter工程，插件会报错

### ISSUE THREAD

**Issue by for7GG** [Fly-Mix/flr-as-plugin#15]
andoridstudio 4.2.1
最新版本的插件
打开flutter工程没问题，打开android工程会报错
```
Plugin 'com.fly-mix.flr' failed to initialize and will be disabled.  Please restart Android Studio.

java.lang.NullPointerException
    at com.flr.command.FlrCommand.initFlagOfShouldSupportNullsafety(FlrCommand.java:67)
    at com.flr.command.FlrCommand.<init>(FlrCommand.java:61)
    at com.flr.FlrApp.<init>(FlrApp.java:14)
    at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
    at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
    at com.intellij.serviceContainer.ConstructorInjectionKt.instantiateUsingPicoContainer(constructorInjection.kt:52)
    at com.intellij.serviceContainer.ComponentManagerImpl.instantiateClassWithConstructorInjection(ComponentManagerImpl.kt:664)
    at com.intellij.serviceContainer.MyComponentAdapter.doCreateInstance(MyComponentAdapter.kt:35)
    at com.intellij.serviceContainer.BaseComponentAdapter.getInstanceUncached(BaseComponentAdapter.kt:113)
    at com.intellij.serviceContainer.BaseComponentAdapter.getInstance(BaseComponentAdapter.kt:67)
    at com.intellij.serviceContainer.BaseComponentAdapter.getInstance$default(BaseComponentAdapter.kt:60)
    at com.intellij.serviceContainer.ComponentManagerImpl.createComponents(ComponentManagerImpl.kt:260)
    at com.intellij.openapi.project.impl.ProjectImpl.init(ProjectImpl.java:110)
    at com.intellij.openapi.project.impl.ProjectManagerImpl.initProject(ProjectManagerImpl.java:177)
    at com.intellij.openapi.project.impl.ProjectManagerExImpl.prepareProject(ProjectManagerExImpl.kt:221)
    at com.intellij.openapi.project.impl.ProjectManagerExI
```

**Comment by YK-Unit** [comment]
> andoridstudio 4.2.1
> 最新版本的插件
> 打开flutter工程没问题，打开android工程会报错
> 
> ```
> Plugin 'com.fly-mix.flr' failed to initialize and will be disabled.  Please restart Android Studio.
> 
> java.lang.NullPointerException
>     at com.flr.command.FlrCommand.initFlagOfShouldSupportNullsafety(FlrCommand.java:67)
>     at com.flr.command.FlrCommand.<init>(FlrCommand.java:61)
>     at com.flr.FlrApp.<init>(FlrApp.java:14)
>     at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
>     at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
>     at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
>     at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
>     at com.intellij.serviceContainer.ConstructorInjectionKt.instantiateUsingPicoContainer(constructorInjection.kt:52)
>     at com.intellij.serviceContainer.ComponentManagerImpl.instantiateClassWithConstructorInjection(ComponentManagerImpl.kt:664)
>     at com.intellij.serviceContainer.MyComponentAdapter.doCreateInstance(MyComponentAdapter.kt:35)
>     at com.intellij.serviceContainer.BaseComponentAdapter.getInstanceUncached(BaseComponentAdapter.kt:113)
>     at com.intellij.serviceContainer.BaseComponentAdapter.getInstance(BaseComponentAdapter.kt:67)
>     at com.intellij.serviceContainer.BaseComponentAdapter.getInstance$default(BaseComponentAdapter.kt:60)
>     at com.intellij.serviceContainer.ComponentManagerImpl.createComponents(ComponentManagerImpl.kt:260)
>     at com.intellij.openapi.project.impl.ProjectImpl.init(ProjectImpl.java:110)
>     at com.intellij.openapi.project.impl.ProjectManagerImpl.initProject(ProjectManagerImpl.java:177)
>     at com.intellij.openapi.project.impl.ProjectManagerExImpl.prepareProject(ProjectManagerExImpl.kt:221)
>     at com.intellij.openapi.project.impl.ProjectManagerExI
> ```

感谢反馈，目前正在处理。

**Comment by YK-Unit** [comment]
> andoridstudio 4.2.1
> 最新版本的插件
> 打开flutter工程没问题，打开android工程会报错
> 
> ```
> Plugin 'com.fly-mix.flr' failed to initialize and will be disabled.  Please restart Android Studio.
> 
> java.lang.NullPointerException
>     at com.flr.command.FlrCommand.initFlagOfShouldSupportNullsafety(FlrCommand.java:67)
>     at com.flr.command.FlrCommand.<init>(FlrCommand.java:61)
>     at com.flr.FlrApp.<init>(FlrApp.java:14)
>     at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
>     at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
>     at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
>     at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
>     at com.intellij.serviceContainer.ConstructorInjectionKt.instantiateUsingPicoContainer(constructorInjection.kt:52)
>     at com.intellij.serviceContainer.ComponentManagerImpl.instantiateClassWithConstructorInjection(ComponentManagerImpl.kt:664)
>     at com.intellij.serviceContainer.MyComponentAdapter.doCreateInstance(MyComponentAdapter.kt:35)
>     at com.intellij.serviceContainer.BaseComponentAdapter.getInstanceUncached(BaseComponentAdapter.kt:113)
>     at com.intellij.serviceContainer.BaseComponentAdapter.getInstance(BaseComponentAdapter.kt:67)
>     at com.intellij.serviceContainer.BaseComponentAdapter.getInstance$default(BaseComponentAdapter.kt:60)
>     at com.intellij.serviceContainer.ComponentManagerImpl.createComponents(ComponentManagerImpl.kt:260)
>     at com.intellij.openapi.project.impl.ProjectImpl.init(ProjectImpl.java:110)
>     at com.intellij.openapi.project.impl.ProjectManagerImpl.initProject(ProjectManagerImpl.java:177)
>     at com.intellij.openapi.project.impl.ProjectManagerExImpl.prepareProject(ProjectManagerExImpl.kt:221)
>     at com.intellij.openapi.project.impl.ProjectManagerExI
> ```

issue已修复，请在Android Studio 插件中心或者官网下载新版本 [Flr v202.3.3.1](https://plugins.jetbrains.com/plugin/13789-flr/versions/stable/121118)
